apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "net4255.fullname" . }}-mongo
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
data:
  MONGO_HOST: "mongodb"
  MONGO_PORT: "{{ .Values.mongodb.port }}"
