{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "net4255.fullname" . }}
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.webnodb | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webnodb
                port:
                  number: 5000
    - host: {{ .Values.ingress.hosts.webdb | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webdb
                port:
                  number: 5000
{{- end }}
