# Default values for the NET4255 lab.

image:
  repository: azerzaa/flask-net4255
  pullPolicy: IfNotPresent

webnodb:
  replicas: 1
  tag: webnodb-v2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 60

webdb:
  replicas: 1
  tag: webdb-v3
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 60
  mongo:
    db: net4255
    collection: visits

mongodb:
  enabled: true
  replicas: 3
  image: mongo:7
  port: 27017
  replicaSet:
    name: "rs0"
  storage:
    size: 512Mi
    storageClassName: longhorn
  networkPolicy:
    enabled: true

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

ingress:
  enabled: true
  className: nginx
  hosts:
    webnodb: webnodb.azaabar.net4255.luxbulb.org
    webdb: webdb.azaabar.net4255.luxbulb.org
