# Default values for the NET4255 lab.

image:
  repository: azerzaa/flask-net4255
  pullPolicy: IfNotPresent

webnodb:
  replicas: 1
  tag: webnodb-v2
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60

webdb:
  replicas: 3
  tag: webdb-v3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
  mongo:
    db: net4255
    collection: visits

mongodb:
  enabled: true
  replicas: 1
  image: mongo:7
  port: 27017
  storage:
    size: 1024Mi
    storageClassName: longhorn
  networkPolicy:
    enabled: true

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"

ingress:
  enabled: true
  className: nginx
  hosts:
    webnodb: webnodb.azaabar.net4255.luxbulb.org
    webdb: webdb.azaabar.net4255.luxbulb.org
